### ISSUE TITLE
Occasional small difference in payouts between mina explorer and api.minastakes.com data provider

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#142]
Identified an issue where failed transactions are still counting toward the user transaction fees.

Fix would be to alter mina explorer data provider to include failure reason from the userCommands, and to skip that userCommand if the failureReason is not null.

e.g. https://github.com/jrwashburn/mina-pool-payout/blob/059218d07fd0f6c416d0dfb03ddeab26194072f3/src/core/dataProvider/dataprovider-minaexplorer/block-queries-gql.ts#L32 should instead be: 

```
 userCommands {
        fee
        failureReason
      }
```
and then the block processor should ignore failure reason = null. 

Example block: 348526, transaction hash CkpYgBAJ2GkHhUudNwUSeA8z71wzGpRRA3QwSeG3t5nBo5LsCLjn5 failed. It is excluded from the archive db queries on api.minastakes, but is not being excluded from other data sources.

**Comment by trevorbernard** [comment]
It has been my observation that the fee for failed transactions are taken regardless. Though on failed payments, the transacted amount remains remains with the sender. Take for example the following block: https://minaexplorer.com/block/3NKd5So3VNqGZtRZiWsti4yaEe1fX79yz5TbfG6jBZqgMnCQQp3R

All transactions failed with non-sufficient funds to create an account. All the transaction fees were sent to the block receiver because either the SNARK work was 0 or there was no SNARK workers to process said transactions.

**Comment by jrwashburn** [comment]
That makes more sense. This is instead a bug in mina-payouts-data-provider which should not be filtering to only applied user transactions. 
https://github.com/jrwashburn/mina-payouts-data-provider/blob/6f6893e9ae21de781562c881f15ac64f2d2311cb/src/database/blockQueryFactory.ts#L93
https://github.com/jrwashburn/mina-payouts-data-provider/blob/6f6893e9ae21de781562c881f15ac64f2d2311cb/src/database/blockQueryFactory.ts#L222

Will patch there.
