### ISSUE TITLE
Filtering low amounts

### ISSUE THREAD

**Issue by EmrePiconbello** [jrwashburn/mina-pool-payout#55]
With the start of mina distribution, there is a possible increase of stakers with low amounts like 0.1, I saw an issue for calculating these for multiple epoch till they reach a certain amount but looks like it's closed this looks like at least a solution to filter low amounts at this stage.

**Comment by jrwashburn** [comment]
There is a filtering solution currently which I'm actively using. https://github.com/jrwashburn/mina-pool-payout#handling-special-accounts---suppressing-or-redirecting-payouts 

Adding a database or other method to track is a bigger piece of work. I think we will get there, but are in the middle of a significant clean up to make this code more maintainable and (more importantly) testable so that we can move faster. In the meantime, suppression is possible.

**Comment by jrwashburn** [comment]
I also re-opened #44 - we need to implement it. If you can confirm the filtering works for you, will you close this?

**Comment by EmrePiconbello** [comment]
I can confirm filtering works but it prints nano minas so you can't even clearly see which addresses are under these limits which makes the filtering process a mess. Also you need to go back and check on the addresses you filter since they might increase. Closing this one to follow on the #44

**Comment by jrwashburn** [comment]
I think I didn't understand what you meant, but do now. So instead of just filtering by address, you also want to simply filter anything below a configured threshold - if payout would be less than X MINA, auto-suppress? If that is what you mean, re-open and we will implement that.

**Comment by EmrePiconbello** [comment]
Yes, it can be if the payout is less than a certain amount or if delegated balance is under a certain amount both of them ended up similar and does the work in this case. I believe the other suggestion for holding till reaching a certain amount will be very complicated because we need to check staking ledgers through 2-3 epoch. Just filtering the amount by reward or delegated would save a lot of time.

**Comment by jrwashburn** [comment]
Sounds good - I think I will make it based on the payout amount.
