### ISSUE TITLE
Change handling of supercharged coinbase

### ISSUE THREAD

**Issue by jrwashburn** [jrwashburn/mina-pool-payout#58]
The current payout calculator choices are biased toward locked tokens and unfairly pay a portion of a supercharged coinbase to the locked tokens, without sharing a relative supercharged portion of the "normal" coinbase with any unlocked accounts in the pool.

After considering a range of options, it seems a better approach would be to alter that payout to simply reserve the supercharged coinbase in a separate pool that is only paid out to the unlocked tokens. That would change the payout waterfall to:

1 - straight pro-rata on the normal (720) coinbase based on the account balances delegated.
2 - straight pro-rata of the subset excluding O1 Labs and Mina Foundation for the fees generated.
3 - straight pro-rata of the subset excluding 01 Labs, Mina Foundation, and locked accounts for the supercharged remainder (additional 720).

This will make the supercharged payout lumpy for the unlocked accounts, but will also guarantee the locked tokens will always receive their full share.

**Comment by EmrePiconbello** [comment]
Can you make it more clear a bit. I remember it should be equal in the long run. If it was favouring locked on how it was doing that.  Wasn't the existing system does the same. What you outlined here?

Also, I have a proposal to just cut out all the fees generated out instead of just the foundation one. My reasoning is I don't believe these fees never reach any significant amount. When there is some high fee like 500 etc. then we will send it back to the owner which mixes up calculation more. :) From the start, I am just suggesting cutting the fees out of the block when they go significantly towards the coinbase because there is always a possibility of 300-500 snark happening on a block. If there is a significant fee increase where snarks are really ending up to something that we had much more competition on snark marketplace which will drive snark prices up and drop the BP's gainfrom it.

**Comment by jrwashburn** [comment]
It was favoring unlocked. The old waterfall was:

1 - pro-rata on the first 720
2 - supercharged weight on the remainder

That meant that locked tokens were sharing in the reward from unlocked, which they should not. That will not happen with the proposed change - and the unlocked tokens will get a big award when an unlocked block is generated, but will not get a "supercharged" allocation against normal blocks as in minaexplorer's initial implementation.

**Comment by jrwashburn** [comment]
Another option may be to skip step w, which I think you may be suggesting -- which leaves the fees to the BP?

**Comment by EmrePiconbello** [comment]
I don't really think fees are adding up to something or will be some amount significant for a long time. On the other hand, it creates a lot of confusion and complications. 

You can pay up to 700 more if it's supercharged for single snark for coinbase tx while the snark fees for transactions can't be higher than the fee user game. It's mostly around 0.01 range which doesn't sum up to any significant amount. Let's say you receive a block with an 1000 mina fee because someone sends it by mistake and you pay it back, Good luck with the calculation. In the future when tx fees increase because of network activity that would increase snark fees as well so even fees increase bp's gain from it never going to be significant.

**Comment by jrwashburn** [comment]
For your fee proposal, are you suggesting that the BP keep the fees? And if they are negative, payout the pool for the full amount anyway and the pool owner takes a loss? Or something else? Not sure what you mean by ignoring fees.

**Comment by EmrePiconbello** [comment]
@jrwashburn my suggestion was since snark fees for transactions are not ending up being something disregarding is probably better. If you hit by a snark fee for coinbase with +5-10 then you are on negative you should calculate that, I am just saying from transactions snark fees I never see any significant amount to even affect something. If snarks price increase then transaction fees going to increase but the majority of these fees go to snark sellers not to block producers.
