### ISSUE TITLE
staking amount of each delegate

### ISSUE THREAD

**Issue by Yong-Uk** [jrwashburn/mina-pool-payout#83]
current payout results show payout and fee of each delegate.
It will be good to show staking amount of each delegate that can be helpful to check the amount of rewards according to the staking amount

**Comment by jrwashburn** [comment]
These details are all written to the payout_details_ file that is written with each run. Since the staking amount can change with each staking ledger, and the keys could unlock mid-epoch, I am not confident that summary data would be useful or correct. All details necessary to validate the calculation are in the payout details file. Any summary attempt would have to reconcile the unlock point, and the staked amount variance across ledgers; therefore, I think providing the detailed data allows operators to do their own post-processing for any validation/testing. 

Finally, I think the -v (verbose) flag will provide the additional detail you are looking for. If that is not the case, feel free to re-open with what additional information would be helpful either in the files or the --verbose mode.
