### ISSUE TITLE
Staking balance

### ISSUE THREAD

**Issue by phdsoon** [jrwashburn/mina-pool-payout#84]
I think showing staking balance is good.
Currently, show "index", "publicKey", "amount", "fee", "amountMina", "feeMina"
I suggest "index", "publicKey", **_"staking balance"_**, "amount", "fee", "amountMina", "feeMina"
As you know "-v" flag show more details but it is not sorted and hard to see for delegators.
But staking amount is changed according to ledger, so.. I'm not sure how to show this challenge.
I think many validator pay rewards in a epoch. yeah.. It's hard thing :)

**Comment by jrwashburn** [comment]
Perhaps as long as the scope is limited to one ledger file, it could add that. We have a lot planned, but will see if that fits in nicely or not.

**Comment by jrwashburn** [comment]
@phdsoon If you don't care about this any more, let's close the issue. If you do, what would be acceptable solutions? 

I think the -v payout details table is the best place to get this and it already has it - on a per-block, per-key basis. Would that meet your needs (if they still exist?) And if so, how would you want it sorted? Is sorting the only issue? Would it be better to just dump it to a csv file or something else? 

I can see a few ways to solve:

1. Just use -verbose, and improve its usability with sorting (perhaps dump to a separate file)
2. Add a new summarizer behind a command line flag that would summarize, but within epoch. I don't want to do this because I'm lazy. It might be nice, but I don't have a ton of free time.
3. Add the stake balance to the current summary table, but leave it blank if the payout run spans more than one epoch. 

My preference is option 1.

**Comment by jrwashburn** [comment]
@phdsoon do you care about or still want this? If so, do you want the staking balance to be the staking balance for that pk, or for the pool in total? What about showing pool % (rounded perhaps to a few digits?)

**Comment by jrwashburn** [comment]
Closing
